# -*- coding: utf-8 -*-
"""part1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r6zHCzmYkxRtnqxIU40ZwNY1HsWW4cda

Data Acquisition, Cleaning, and Exploratory Analysis -Part 1
Refer README.md
"""

#task 1 load data
import pandas as pd

# Load the dataset (replace 'laptops.csv' with your file path)
df = pd.read_csv('laptop_data.csv')

# View the first 5 rows
print("--- First 5 Rows ---")
print(df.head())

# Get basic information about columns and data types
print("\n--- Dataset Info ---")
print(df.info())
print(df.describe())

#task 2 Null value analysis
import pandas as pd

df = pd.read_csv("laptop_data.csv")
missing_count = df.isnull().sum()
missing_percentage = (df.isnull().sum() / df.shape[0]) * 100

missing_summary = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing Percentage": missing_percentage.round(2)
})

print(missing_summary)
high_null = missing_summary[missing_summary["Missing Percentage"] > 20]

print("Columns with more than 20% missing values:")
print(high_null)
numeric_cols = df.select_dtypes(include='number').columns

for col in numeric_cols:
    null_percent = (df[col].isnull().sum() / len(df)) * 100

    if null_percent <= 20:
        df[col] = df[col].fillna(df[col].median())

print("Missing values filled.")
remaining_nulls = df.isnull().sum()

print(remaining_nulls[remaining_nulls > 0])

"""laptop_data1.csv created because no dupicates in laptop_data.csv and found few duplicates,missing values,nanchecked and clean datset produced. Here no duplicates found. Both data sets loaded (duplicates created manually )and checked verified."""

#task 3 Duplicate detection and removal
# Count duplicate rows

df = pd.read_csv('laptop_data.csv')
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

#task 3 Duplicate detection and removal
# Count duplicate rows

df = pd.read_csv('laptop_data1.csv')
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

# task 3Count duplicate rows
duplicate_count = df.duplicated().sum()
print("Duplicate rows:", duplicate_count)

# Null percentage before removing duplicates
null_before = (df.isnull().sum() / len(df)) * 100

# Remove duplicate rows
df_clean = df.drop_duplicates()

# Count rows removed
rows_removed = len(df) - len(df_clean)
print("Rows removed:", rows_removed)

# Null percentage after removing duplicates
null_after = (df_clean.isnull().sum() / len(df_clean)) * 100

# Compare null percentages
comparison = pd.DataFrame({
    "Before (%)": null_before.round(2),
    "After (%)": null_after.round(2)
})

print(comparison)

# Check whether null percentages changed
if null_before.equals(null_after):
    print("Null percentages did not change after removing duplicates.")
else:
    print("Null percentages changed after removing duplicates.")

#task 4data type correction
import pandas as pd

# Load dataset
df = pd.read_csv("laptop_data1.csv")

# Display original data types
print("Original Data Types:\n")
print(df.dtypes)

# Memory usage before conversion
memory_before = df.memory_usage(deep=True).sum()
print("\nMemory usage before conversion:", memory_before, "bytes")

# -----------------------------
# Data Type Corrections
# -----------------------------

# Convert Ram from object (e.g., '8GB') to numeric
df["Ram"] = pd.to_numeric(
    df["Ram"].str.replace("GB", "", regex=False),
    errors="coerce"
)

# Convert repetitive string columns to category
df["Company"] = df["Company"].astype("category")
df["TypeName"] = df["TypeName"].astype("category")
df["OpSys"] = df["OpSys"].astype("category")

# -----------------------------
# Display updated data types
# -----------------------------

print("\nUpdated Data Types:\n")
print(df.dtypes)

# Memory usage after conversion
memory_after = df.memory_usage(deep=True).sum()
print("\nMemory usage after conversion:", memory_after, "bytes")

# Memory saved
print("Memory saved:", memory_before - memory_after, "bytes")
#["Company"] = df["Company"].astype("category"

#task 5 descriptive stat (skew)
df = pd.read_csv("laptop_data1.csv")
df["Ram"] = pd.to_numeric(df["Ram"].str.replace("GB", "", regex=False), errors="coerce")
print(df.describe())
skewness = df.select_dtypes(include="number").skew()

print("Skewness of numeric columns:\n")
print(skewness)
highest_skew_col = skewness.abs().idxmax()
highest_skew_value = skewness[highest_skew_col]

print("\nColumn with highest absolute skewness:", highest_skew_col)
print("Skewness value:", highest_skew_value)

#task 6  outlier detection
import pandas as pd

df = pd.read_csv("laptop_data.csv")

# Convert Ram to numeric
df["Ram"] = pd.to_numeric(df["Ram"].str.replace("GB", "", regex=False), errors="coerce")
# Numeric columns to analyze
columns = ["Price", "Ram"]

for col in columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print("\nColumn:", col)
    print("Q1 =", Q1)
    print("Q3 =", Q3)
    print("IQR =", IQR)
    print("Lower Bound =", lower_bound)
    print("Upper Bound =", upper_bound)
    print("Number of Outliers =", len(outliers))

#task 7 visualise
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
# Load dataset
df = pd.read_csv("laptop_data.csv")
os.makedirs("Part1", exist_ok=True)
# Convert Ram to numeric
df["Ram"] = pd.to_numeric(df["Ram"].str.replace("GB", "", regex=False), errors="coerce")
#line chart
plt.figure(figsize=(8,5))
plt.plot(df.index, df["Price"])
plt.title("Line Plot of Laptop Prices")
plt.xlabel("Row Index")
plt.ylabel("Price")
plt.savefig("Part1/line_plot.png", dpi=300, bbox_inches="tight")
plt.show()
#Bar Chart (Average Price by Company)
avg_price = df.groupby("Company")["Price"].mean()

plt.figure(figsize=(10,5))
avg_price.plot(kind="bar")
plt.title("Average Laptop Price by Company")
plt.xlabel("Company")
plt.ylabel("Average Price")
plt.savefig("Part1/bar_chart.png", dpi=300, bbox_inches="tight")
plt.show()
#histogram (Most Skewed Numeric Column)
plt.figure(figsize=(8,5))
sns.histplot(df["Price"], bins=20)
plt.title("Histogram of Laptop Prices")
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.savefig("Part1/histogram.png", dpi=300, bbox_inches="tight")
plt.show()
#Scatter Plot (Ram vs Price)
plt.figure(figsize=(8,5))
sns.scatterplot(x="Ram", y="Price", data=df)
plt.title("Scatter Plot of RAM vs Price")
plt.xlabel("RAM (GB)")
plt.ylabel("Price")
plt.savefig("Part1/scatter_plot.png", dpi=300, bbox_inches="tight")
plt.show()
#Box plot(price by company)
plt.figure(figsize=(12,6))
sns.boxplot(x="Company", y="Price", data=df)
plt.title("Price Distribution by Company")
plt.xlabel("Company")
plt.ylabel("Price")
plt.xticks(rotation=45)
plt.savefig("Part1/box_plot.png", dpi=300, bbox_inches="tight")
plt.show()

#task 8  correlation
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Load dataset
df = pd.read_csv("laptop_data.csv")

# Convert Ram to numeric
df["Ram"] = pd.to_numeric(df["Ram"].str.replace("GB", "", regex=False), errors="coerce")

# Select numeric columns
numeric_df = df.select_dtypes(include="number")

# Correlation matrix
corr_matrix = numeric_df.corr()

print("Correlation Matrix:\n")
print(corr_matrix)

# Plot heatmap
plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

# Find the pair with the highest absolute correlation
corr = corr_matrix.abs()

# Ignore self-correlation (diagonal)
np.fill_diagonal(corr.values, 0)

highest_pair = corr.unstack().idxmax()
highest_value = corr.unstack().max()

print("\nHighest Absolute Correlation:")
print("Variables:", highest_pair)
print("Correlation Value:", highest_value)

#task 9imputation strategy comparison
import pandas as pd

# Load dataset
df = pd.read_csv("laptop_data.csv")

# Convert Ram to numeric
df["Ram"] = pd.to_numeric(df["Ram"].str.replace("GB", "", regex=False), errors="coerce")

# Convert Price to numeric (if required)
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

# Calculate skewness
skewness = df.select_dtypes(include="number").skew().abs()

# Get the two columns with highest absolute skewness
top2_cols = skewness.sort_values(ascending=False).head(2).index

print("Two numeric columns with highest absolute skewness:")
print(top2_cols)

# Mean and median before imputation
for col in top2_cols:
    print("\nColumn:", col)
    print("Mean   :", df[col].mean())
    print("Median :", df[col].median())

# Fill remaining missing values using the median
for col in top2_cols:
    df[col] = df[col].fillna(df[col].median())

# Verify that no missing values remain
print("\nRemaining missing values:")
print(df[top2_cols].isnull().sum())

#Task 9 spearman rank correlation
import pandas as pd

# Load dataset
df = pd.read_csv("laptop_data.csv")

# Convert Ram to numeric
df["Ram"] = pd.to_numeric(df["Ram"].str.replace("GB", "", regex=False), errors="coerce")

# Convert Price to numeric (if required)
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

# Calculate skewness
skewness = df.select_dtypes(include="number").skew().abs()

# Get the two columns with highest absolute skewness
top2_cols = skewness.sort_values(ascending=False).head(2).index

print("Two numeric columns with highest absolute skewness:")
print(top2_cols)

# Mean and median before imputation
for col in top2_cols:
    print("\nColumn:", col)
    print("Mean   :", df[col].mean())
    print("Median :", df[col].median())

# Fill remaining missing values using the median
for col in top2_cols:
    df[col] = df[col].fillna(df[col].median())

# Verify that no missing values remain
print("\nRemaining missing values:")
print(df[top2_cols].isnull().sum())

#show difference between them
df_demo = df.copy()

# Create missing values
df_demo.loc[0:5, "Price"] = None

print("Mean:", df_demo["Price"].mean())
print("Median:", df_demo["Price"].median())

# Mean imputation
mean_df = df_demo.copy()
mean_df["Price"] = mean_df["Price"].fillna(mean_df["Price"].mean())

# Median imputation
median_df = df_demo.copy()
median_df["Price"] = median_df["Price"].fillna(median_df["Price"].median())

print(mean_df["Price"].head(10))
print(median_df["Price"].head(10))

#task 9 show diff, confirm no values
import pandas as pd

# Load dataset
df = pd.read_csv("laptop_data.csv")

# Convert Ram to numeric
df["Ram"] = pd.to_numeric(df["Ram"].str.replace("GB", "", regex=False), errors="coerce")

# Select numeric columns
numeric_df = df.select_dtypes(include="number")

# Find the two columns with the highest absolute skewness
skewness = numeric_df.skew()
top2_cols = skewness.abs().sort_values(ascending=False).head(2).index

print("Two most skewed numeric columns:", list(top2_cols))

# Print mean and median side by side
print("\nMean and Median:")
for col in top2_cols:
    print(f"{col:10} Mean = {df[col].mean():.2f}    Median = {df[col].median():.2f}")

# Median imputation
for col in top2_cols:
    df[col] = df[col].fillna(df[col].median())

# Verify no missing values remain
print("\nRemaining missing values:")
print(df[top2_cols].isnull().sum())

#task 9 grouped aggregation
import pandas as pd

# Load dataset
df = pd.read_csv("laptop_data.csv")

# Group by Company and calculate mean, standard deviation and count of Price
group_stats = df.groupby("Company")["Price"].agg(["mean", "std", "count"])

print(group_stats)

# Group with highest mean
highest_mean_group = group_stats["mean"].idxmax()
highest_mean = group_stats["mean"].max()

# Group with highest standard deviation
highest_std_group = group_stats["std"].idxmax()
highest_std = group_stats["std"].max()

# Ratio of highest mean to lowest mean
lowest_mean = group_stats["mean"].min()
ratio = highest_mean / lowest_mean

print("\nGroup with Highest Mean:", highest_mean_group)
print("Highest Mean:", highest_mean)

print("\nGroup with Highest Standard Deviation:", highest_std_group)
print("Highest Standard Deviation:", highest_std)

print("\nHighest Mean / Lowest Mean Ratio:", round(ratio, 2))

# task 10 SAVE then used in part 2 & 3
# Save the cleaned dataset
df.to_csv("cleaned_data.csv", index=False)

print("Dataset saved successfully as cleaned_data.csv")
cleaned_df = pd.read_csv("cleaned_data.csv")

print(cleaned_df.head())
print(cleaned_df.shape)

#saved b4cleaning -show ramtext or numeric
import pandas as pd

# Check the data type
if df["Ram"].dtype == "object":
    df["Ram"] = pd.to_numeric(
        df["Ram"].str.replace("GB", "", regex=False),
        errors="coerce"
    )

print("Ram data type:", df["Ram"].dtype)
print(df["Ram"].head())

# Save the cleaned dataset
df.to_csv("cleaned_data.csv", index=False)

#null percentage table
import pandas as pd

# Load dataset
df = pd.read_csv("laptop_data1.csv")

# Calculate missing count and percentage
missing_count = df.isnull().sum()
missing_percentage = (missing_count / len(df)) * 100

# Create summary table
null_table = pd.DataFrame({
    "Missing Count": missing_count,
    "Null Percentage (%)": missing_percentage.round(2)
})

# Print all columns
print(null_table)